In [1]:
import numpy as np

---
### 4 - Arrays vs Lists
---

In [2]:
L = [1,2,3]
A = np.array([1,2,3])

In [3]:
for e in L:
    print(e)

1
2
3


In [4]:
for e in A:
    print(e)

1
2
3


In [5]:
L.append(4)

In [6]:
L

[1, 2, 3, 4]

In [30]:
# A.append(5)
# Size of a numpy array is fixed.

In [10]:
L+[5]

[1, 2, 3, 4, 5]

In [13]:
A+np.array([4])
# It sums up the 4 in each element

array([5, 6, 7])

In [16]:
A + np.array([4,5,6])

array([5, 7, 9])

In [17]:
2*A

array([2, 4, 6])

In [18]:
2*L

[1, 2, 3, 4, 1, 2, 3, 4]

In [19]:
L+L

[1, 2, 3, 4, 1, 2, 3, 4]

In [21]:
L2 = []
for e in L:
    L2.append(e+3)
L2

[4, 5, 6, 7]

In [22]:
L2 = [e+3 for e in L]
L2

[4, 5, 6, 7]

In [23]:
# L**2
A**2

array([1, 4, 9], dtype=int32)

In [24]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [25]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [26]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [28]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

---
### 5 - Dot Products
---

In [29]:
a = np.array([1,2])
b = np.array([3,4])

In [31]:
dot = 0
for e,f in zip(a,b):
    dot += e*f
dot

11

In [36]:
print(a.dot(b))
print(np.dot(a,b))
print(a @ b)

11
11
11


In [35]:
print(np.sum(a*b))
print((a*b).sum())

11
11


In [37]:
magnitude = np.sqrt((a*a).sum())
magnitude

2.23606797749979

In [38]:
np.linalg.norm(a)

2.23606797749979

In [40]:
cosang = a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosang

0.9838699100999074

In [41]:
angle = np.arccos(cosang)
angle

0.17985349979247847

---
### 6 - Speed Test
---

In [44]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slowDotProduct(a,b):
    result = 0
    for e,f in zip(a,b):
        result += e*f
    return result
t0 = datetime.now()
for t in range(T):
    slowDotProduct(a,b)
dt1 = datetime.now()-t0

t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now()-t0

print("dt1/dt2 : ", dt1.total_seconds()/dt2.total_seconds())

dt1/dt2 :  45.35968634537505


---
### 7 - Matrices
---

In [45]:
L = [[1,2],
    [3,4]]
L

[[1, 2], [3, 4]]

In [47]:
L[0][1]

2

In [48]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [50]:
print(A[0][1])
print(A[0,0])

2
1


In [51]:
A[:,0]

array([1, 3])

In [52]:
A.T

array([[1, 3],
       [2, 4]])

In [53]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [54]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [55]:
B = np.array([[1,2,3],[4,5,6]])

In [56]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [58]:
np.linalg.det(A)

-2.0000000000000004

In [59]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [61]:
np.linalg.inv(A).dot(A)     # identity

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [62]:
np.trace(A)

5

In [63]:
np.diag(A)

array([1, 4])

In [64]:
np.diag([1,3])

array([[1, 0],
       [0, 3]])

In [65]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [66]:
Lam , V = np.linalg.eig(A)

In [67]:
V[:,0]*Lam[0] == A@V[:,0]

array([ True, False])

In [68]:
V[:,0]*Lam[0], A@V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [69]:
np.allclose(V[:,0] * Lam[0], A@V[:,0])

True

---
### 8 - Solving Linear Systems
---
x + y = 2200 <br>
1.5x + 4y = 5050

In [70]:
# inverse is slower and less accurate
A = np.array([[1,1],[1.5,4]])
b = np.array([2200, 5050])

In [72]:
np.linalg.solve(A,b)

array([1500.,  700.])

---
### 9 - Generating Data
---

In [73]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.ones((2,3)) * 10       # There is also function called tens

array([[10., 10., 10.],
       [10., 10., 10.]])

In [77]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.random.random()

0.9134855489191612

In [79]:
np.random.random((2,3))

array([[0.54154911, 0.29916059, 0.61224618],
       [0.79905667, 0.83533979, 0.73838059]])

In [80]:
np.random.randn(2,3)

array([[-2.3919147 , -0.61202049,  1.33167694],
       [ 0.42730617,  1.00124698,  0.06512148]])

In [84]:
R = np.random.randn(10000)
print(R.mean())
print(R.var())
print(R.std())       # sqrt of varience

-0.008259067151435094
1.0136825601558201
1.006818037261858


In [89]:
R = np.random.randn(10000, 3)
R.mean(axis=0)

array([-0.00542481,  0.01021234, -0.01668746])

In [91]:
R.mean(axis=1).shape

(10000,)

In [92]:
np.cov(R).shape

(10000, 10000)

In [93]:
np.cov(R.T)

array([[ 9.90288073e-01, -1.63565827e-02, -1.32051863e-03],
       [-1.63565827e-02,  9.94284247e-01, -2.72153814e-04],
       [-1.32051863e-03, -2.72153814e-04,  9.81555698e-01]])

In [94]:
np.cov(R, rowvar = False)

array([[ 9.90288073e-01, -1.63565827e-02, -1.32051863e-03],
       [-1.63565827e-02,  9.94284247e-01, -2.72153814e-04],
       [-1.32051863e-03, -2.72153814e-04,  9.81555698e-01]])

In [96]:
np.random.randint(0,10,size=(3,3))

array([[7, 9, 4],
       [0, 3, 4],
       [0, 2, 8]])